  name: Automated tests

  on:
    workflow_dispatch:
      inputs:
        deployment_target:
          description: Choose target
          required: true
          default:
            type: choice
            options:
              - first_test
              - second_test


  jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: setup/Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"
        - name: Install Chrome
          run: sudo apt-get install google-chrome-stable
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: first_test
          if: "github.event.inputs.target == 'first_test'"
          run: pytest -m github_actions
        - name: second_test
          if: "github.event.inputs.target == 'second_test'"
          run: pytest -m github_actions_1